services:
  - type: web
    name: weatherforge-web
    runtime: ruby
    region: oregon
    plan: free
    branch: main
    buildCommand: >
      SKIP_REDIS=true bundle install &&
      SKIP_REDIS=true bundle exec rake assets:precompile &&
      bundle exec rake db:migrate &&
      bundle exec rake solid_queue:install:migrations &&
      bundle exec rake solid_cable:install:migrations &&
      bundle exec rake solid_cache:install:migrations &&
      bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: common-projects-postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
    healthCheckPath: /up
    autoDeploy: true

databases:
  - name: common-projects-postgres
    region: oregon
    plan: free
    databaseName: common_projects_postgres_production
    user: renderuser
    postgresMajorVersion: "17"
