services:
  - type: web
    name: weatherforge-web
    runtime: ruby
    region: oregon
    plan: free
    branch: main
    buildCommand: >
      bundle install &&
      bundle exec rake assets:precompile &&
      bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: common-projects-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: conscious-helicopter
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
    healthCheckPath: /up
    autoDeploy: true

  - type: worker
    name: weatherforge-sidekiq
    runtime: ruby
    region: oregon
    plan: free
    branch: main
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: common-projects-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: conscious-helicopter
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
    autoDeploy: true

databases:
  - name: common-projects-postgres
    region: oregon
    plan: free
    databaseName: common_projects_postgres_production
    user: renderuser
    postgresMajorVersion: "17"
