---
:verbose: false
:timeout: 60
:concurrency: 5
:max_retries: 5

:queues:
  - default
  - [critical, 2]

:schedule:
  sync_weather_job:
    cron: "*/5 * * * *"
    class: SyncWeatherJob
    queue: default
    description: "Sync all weather data from 7 Open Meteo APIs every 5 minutes"
